# Dataset Parameters
DATA:
  ROOT_DIR: "/media/data/tridiv/epic"
  RGB_DIR_PREFIX: "symlinks"
  FLOW_DIR_PREFIX: "symlinks"
  AUDIO_DIR_PREFIX: "audio"
  MODALITY: ["RGB", "Flow", "Spec"]
  VID_FPS: 60
  FLOW_FPS: 30
  OUT_FPS: 10
  RGB_FILE_FMT: "img_{:010d}.jpg"
  FLOW_FILE_FMT: "{}_{:010d}.jpg"
  AUDIO_FILE_FMT: "{}.wav"
  FLOW_WIN_LENGTH: 5
  SAMPLING_RATE: 24000
  AUDIO_LENGTH: 1.279
  TEST_SCALE_SIZE: 256
  TEST_CROP_SIZE: 224
  VID_LIST: "/media/data/tridiv/epic/vid_list_mini.txt"
  OUT_DIR: "/media/data/tridiv/epic/features"
# Model Parameters
MODEL:
  ARCH: "BNInception"
  NUM_CLASSES: [125, 352]
  CHECKPOINT: "/media/data/tridiv/epic_fusion_feature_extractor/weights/model_best.pth"
# Misc
NUM_WORKERS: 8